# Generated by Django 4.0.1 on 2022-01-27 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Compound's representation")),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name="Model's name")),
                ('description', models.CharField(max_length=10000, verbose_name="Model's description")),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Parameter's name")),
                ('value', models.FloatField(verbose_name="Parameter's value")),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='density.compound')),
            ],
        ),
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name="Graph's label")),
                ('image', models.ImageField(upload_to='', verbose_name="Graph's image")),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='density.predictivemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Equations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name="Equation's number")),
                ('equation', models.ImageField(upload_to='', verbose_name="Equation's image")),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='density.predictivemodel')),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='density.predictivemodel'),
        ),
        migrations.CreateModel(
            name='AbsoluteParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Parameter's name")),
                ('value', models.FloatField(verbose_name="Parameter's value")),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='density.predictivemodel')),
            ],
        ),
    ]
