# Generated by Django 4.0.1 on 2022-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('density', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absoluteparameter',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name="Parameter's name"),
        ),
        migrations.AlterField(
            model_name='absoluteparameter',
            name='value',
            field=models.FloatField(null=True, verbose_name="Parameter's value"),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name="Compound's representation"),
        ),
        migrations.AlterField(
            model_name='equations',
            name='number',
            field=models.IntegerField(null=True, verbose_name="Equation's number"),
        ),
        migrations.AlterField(
            model_name='graphs',
            name='label',
            field=models.CharField(max_length=100, null=True, verbose_name="Graph's label"),
        ),
    ]
