# Generated by Django 4.0.1 on 2022-01-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('density', '0003_compound_esther_type_alter_compound_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equations',
            new_name='Equation',
        ),
        migrations.RenameModel(
            old_name='Graphs',
            new_name='Graph',
        ),
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
    ]
