# Generated by Django 4.0.1 on 2022-01-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('density', '0004_rename_equations_equation_rename_graphs_graph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictivemodel',
            name='description',
            field=models.TextField(verbose_name="Model's description"),
        ),
    ]
