# Generated by Django 4.0.1 on 2022-02-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('density', '0005_alter_predictivemodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='model_id',
            new_name='compound_id',
        ),
    ]
