# Generated by Django 4.0.1 on 2022-02-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
