# Generated by Django 4.0.1 on 2022-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default='Home', max_length=50, verbose_name='Home name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='intro',
            field=models.TextField(verbose_name='Introduction'),
        ),
    ]
